### ISSUE TITLE
Required Libraires

### ISSUE THREAD

**Issue by lincolnstophat** [flancast90/camview#1]
Hello,
     I have just downloaded the zip folder and attempted to " download the required libs" but was unsuccessful. Can you help me understand what you mean by download the required libs? I read thru the read.me but could not find any further information. Thanks!

**Comment by flancast90** [comment]
> Hello, I have just downloaded the zip folder and attempted to " download the required libs" but was unsuccessful. Can you help me understand what you mean by download the required libs? I read thru the read.me but could not find any further information. Thanks!

sure! 
You should be able to install them with 
``pip install ast requests selenium climage cv2 multiprocessing argparse``, (assumin you have pip installed already). If you run the program and get a dependency issue, just find the specific package not installed and run ``pip install DEPENDENCY_NAME`` to get it.

If you have any further issues with this, I will be able to help more via discord (my username is BLUND3R#0088), where I can screen share the process.

**Comment by flancast90** [comment]
Further in this issue, I just merged a pull request which will allow you to install them easier. 

`pip install -r requirements.txt`
