### ISSUE TITLE
Won't launch!?

### ISSUE THREAD

**Issue by Hardcore0bject** [flancast90/camview#2]
└─$ python camview.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/camview-main/camview.py", line 15, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Hardcore0bject** [comment]
Using Kali 2022.2 - Python 3.9.10

**Comment by Hardcore0bject** [comment]
Had some trouble installing dependencies, but think they are all there now. Your cli instruction 'pip install ast requests selenium climage cv2 multiprocessing argparse' throws some errors as some are already preinstalled and break the command, and others didn't work. Example -  needed to install OpenCV via  'pip install opencv-python' as you can't use pip to install cv2, that's only for importing the module. Complete newb here, just figuring it out as I go, with google as my friend. Need help with this last part. Have already installed Chrome for Kali in case some drivers were missing.

**Comment by flancast90** [comment]
Looks like the main issue is with selenium. Try and download the chromedriver version matching your chrome://version from https://sites.google.com/chromium.org/driver/. 

You will want to put it in one of the directories output by `echo $PATH `, but if not you can add it to PATH by doing `export PATH=/path/to/chromedriver:$PATH
`
